language: node_js
node_js:
  - "7"

install:
  - yarn install
  - yarn flow-typed install

script:
  - yarn run lint
  - yarn run flow

deploy:
  on:
    branch: master
  provider: script
  script:
    - yarn build && now --public --token $NOW_TOKEN build && now alias --token $NOW_TOKEN
